### ISSUE TITLE
Using UndoManager to implement "revert" to a snapshot.

### ISSUE THREAD

**Issue by nc** [yjs/yjs#350] opened 2021-11-24 16:48 UTC
**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
Using UndoManager to 'revert' to a snapshot results in a loss of data. I tried following the approach described here to implement a 'revert' action: https://discuss.yjs.dev/t/is-there-a-way-to-revert-to-specific-version/379/3?u=nc1 

**To Reproduce**
[1. https://codesandbox.io/s/yjs-restore-using-undo-manager-issue-dr9on?file=/src/App.tsx
](https://codesandbox.io/s/yjs-multiple-map-set-ne35u?file=/src/App.tsx)

**Expected behavior**
Expect `doc.getMap('foo').toJSON() === { "hello": "world" }

**Environment Information**
 - Chrome / Node
 - YJS v13.5.22

**Additional context**

**Comment by dxiao** [comment] 2022-02-07 04:17
Just lurking, but I think this issue got fixed in https://github.com/yjs/yjs/releases/tag/v13.5.25 . If you update the yjs dependency in your sandbox to that version, you should see your problem gone.

**Comment by konstantin24121** [comment] 2022-03-29 09:05
@nc thanks dude, your implementation explains me how revert works!

**Comment by dmonad** [comment] 2022-03-29 09:45
Yep, thanks @dxiao. The issue is fixed when upgrading yjs in the codesandbox.

Thanks @nc for creating the sandbox!

**Closed by dmonad** 2022-03-29 09:45 UTC
Labels: bug
