### ISSUE TITLE
getAttribute on new XMLElement always returns undefined

### ISSUE THREAD

**Issue by tommoor** [yjs/yjs#257] opened 2020-11-05 01:45 UTC
**Describe the bug**
Use `setAttribute` and `getAttribute` on an element before it is "integrated" into a document results in `undefined`. This bug also applies to `toArray` returning `undefined` instead of the elements children.

**To Reproduce**

```javascript
const element = new Y.XmlElement("paragraph");
element.setAttribute("key", "value");
console.log(element.getAttribute("key"));
```

Logs `undefined`

**Expected behavior**

Log "value" – I believe that the `getters` should also consider the internal `_prelim` fields.

**Comment by dmonad** [comment] 2020-11-08 01:04
This is a duplicate of #207

**Closed by dmonad** 2020-11-08 01:04 UTC
Labels: bug
