### ISSUE TITLE
BREAKING CHANGE in patch version

### ISSUE THREAD

**Issue by lodka** [yjs/yjs#517] opened 2023-03-31 13:17 UTC
After updating yjs from version 13.5.50 to 13.5.51 breaking change was introduced. 
The changes are in package.json. The "engines" field was added that has specific versions of node specified.

Now I can't build my project as it depends on the library(from jupyterlab repo) that depends on yjs and unfortunatelly I'm limited to node 14.

Error message: 
`error yjs@13.5.51: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.3"`

I know that I can freeze version in package.json, but because I also need to build jupyterlab which still depends on yjs, this is still failing my build.

That change is really strange as it's just a patch version and it shouldn't break builds and/or pipelines.

**Comment by dmonad** [comment] 2023-03-31 13:31
Duplicate of #513 . Please comment there

**Closed by dmonad** 2023-03-31 13:31 UTC
Labels: bug
