### ISSUE TITLE
decoder.arr.subarray is not a function

### ISSUE THREAD

**Issue by danieldahan** [yjs/yjs#251] opened 2020-10-25 14:09 UTC
Hi, 

I am not sure how to reproduce this issue, since in my setup, once I restart the server, which is required every time I try and dive into this issue, I lose my data. Later on this will be fixed, but for now it is not ideal. That said, I get this error every so often, and not sure if there is bad text, or something that triggers it, but it also does state that the function doesn't even exist. 

If you can shed some light on this, or if it is better for the discussion board, please let me know, and I will be happy to move it over. Thank you!

<img width="832" alt="Screen Shot 2020-10-25 at 8 04 54 AM" src="https://user-images.githubusercontent.com/9982123/97109531-5e219a80-1699-11eb-903b-f46e0cfc23a9.png">

**Comment by danieldahan** [comment] 2020-10-27 02:48
It seems that when I am passing attributes, in the form of 

```
{ insert: 'some text', attributes: { bold: true } }
```

and the "true" value is not a string, it causes this problem. 

Should I be using strings when being sent over, or is the encoding handled?

As for the editor, I am using one that I am building... so not sure if this was internally handled in other editors. 

Thank you!

**Comment by dmonad** [comment] 2020-10-31 03:50
Hi @danieldahan , any kind of JSON-encodable value is fine. Additionally, lib0/encoding also supports ArrayBuffers, Uint8Arrays, BigInt, and `undefined`. 

Could you please help me to reproduce this issue? For that, it would be helpful if you would fill out the issue template. Apparently, the method `subarray` does not exist in your environment. Which environment do you use?

**Comment by danieldahan** [comment] 2020-10-31 17:23
@dmonad yes, for sure. I am using CentOs 8, with Node.js (v12.16.3), where I have encountered this issue in that environment, and on my clients/browsers Chrome, Safari, and FireFox. I pass non-encoded attribute objects to the `text.applyDelta` method.  

```
{ bold: true, key: "string" }
```

When I stringified the "true" value, all seemed to be fine.

**Comment by dmonad** [comment] 2020-11-01 22:46
Okay, thanks.. I also need reproducible steps so I can debug this issue. Several editor bindings use `{bold:true}` as formatting attributes (e.g. the y-quill binding). It is very well tested, and I can't reproduce your problem without more details. Could you please fill out the complete issue template?

**Comment by danieldahan** [comment] 2020-11-02 12:34
Yes, as mentioned, I am making my own editor, and I may be facing an issue with how the data is transferred from my delta to list to Yjs. I had closed the issue for that reason, until I had 100% reproducible steps. That said, the `subarray` not existing is an issue, and I can dive deeper into the Yjs code and see if I can establish concrete steps for you. You are welcome to keep this open for now, and I will get to the bottom of it. You are also welcome to close it, and I will comment what I discovered once I know.

**Comment by dmonad** [comment] 2020-11-02 12:42
Okay sounds good 👍

**Comment by michlschmitt** [comment] 2020-11-04 21:37
I encountered the same error. I use https://github.com/BitPhinix/slate-yjs and https://github.com/BitPhinix/slate-yjs-example. The error occurs when copying and pasting content fast and several times in a row. It throws the error on the remote document when applying the changes. @dmonad do you mind and give it another look? Thanks 🙏

**Comment by michlschmitt** [comment] 2020-11-05 10:19
I could dig deeper. The error occurs when text is inserted. It works fine with one character, but when two or more characters are inserted at the same time, it throws the error. The SlateJS editor schema looks like this:

`
[
   {
     "children": [{"text":""}],
     "id":"4e0d1740-8143-4bec-a2f1-a755df0852b5",
     "type":"TEXT","class":"DEFAULT",
     "purpose":"DEFAULT"
   }
]
`

The new text is added on children > text, which could be the subarray of the yjs doc, I assume.

Here you can find the repository for testing: [](https://github.com/michlschmitt/yjs-slate-example )

The data is shared via localStorage. In Client.js, you find the Editor instance and in the collaboration folder the yjs doc handling. When you initialize the project and open the browser console, the error gets logged when inserting text.

Please let me know if you need further info... Thanks!

**Comment by dmonad** [comment] 2020-11-10 15:28
Thanks @michlschmitt  for providing reproducible steps, I'll have a look.

**Comment by danieldahan** [comment] 2020-11-11 01:20
@michlschmitt yes thank you!

**Comment by dmonad** [comment] 2020-11-11 10:57
@michlschmitt & @danieldahan 

The error occurs because Y.applyUpdate is called with a JSON object as the update message, instead of an Uint8Array.

In `with-yjs.js#67`:

```js
  collabEditor.receiveRemoteChanges = (incomingDoc) => {
    const data = JSON.parse(incomingDoc); // Yjs expects a Uint8Array, not a JSON object
    CollaborationEditor.applyRemoteChanges(collabEditor, data); // this function calls Y.applyUpdate(ydoc, data)
  };
```

Uint8Array has the method `.subarray`, and JSON objects do not. This issue shouldn't happen when you use one of the Yjs providers that implement the sync protocol correctly.

The demo looks awesome, but I think you could implement it more efficiently. It is weird to me that it takes a few seconds until both editors are synced. This could sync immediately ^^

How much of this code was created by you @michlschmitt ? Maybe we should include @BitPhinix: I'm a bit concerned about some performance aspects of the demo code.

* JSON encoding of binary data has some significant overhead. While `Uint8Array([255])` only consumes 1 byte, with no encoding overhead, `"{ 0: 255 }"` consumes at least 20 bytes with some significant parsing overhead (parsing large structures as JSON is really bad; also the json encoding will consume more memory as the index grows). If you want to store the document in localstorage, you should use Base64 encoding (look it up, it's a common solution to the problem). Better yet, you could use y-indexeddb to store the document locally (It stores incremental updates and has a lot of awesome optimizations).
* Every time something changes, the demo encodes the complete document to an update message. Instead you should listen to incremental updates using `ydoc.on('update', (smallUpdateMessage) => {})`.
* Cursors are stored on the Yjs document. This adds some significant overhead, because every time the cursor position is changed, you store additional data in the Yjs document that needs to be persisted forever. This also requires complicated bookkeeping to remove users that are currently offline. There is a better solution. The other editor bindings use the Awareness CRDT: https://docs.yjs.dev/getting-started/adding-awareness

I'm going to close this ticket for now. If you have any questions, feel free to continue discussing or ping me directly. I really like the slate-yjs module and I'd love to help you make it more performant.

**Closed by dmonad** 2020-11-11 10:57 UTC
Labels: bug

**Comment by danieldahan** [comment] 2020-11-17 23:02
@dmonad Thank you for the investigation and comment details.

**Comment by danieldahan** [comment] 2020-11-22 16:37
@dmonad I found that passing in this operation causes the decoder issue. Any ideas if this is an issue, or if I should be doing something else?
 
```
ytext.insert(0, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', {})

```

**Comment by dmonad** [comment] 2020-11-22 19:00
Hi @danieldahan ,

Are you sure that I get an error when I paste the above code? It seems very unlikely to me. I debugged your code at no cost in my free time. Though the attention I can pay at stuff like this is very limited. Please only reopen this issue if you don't know further. I'm certain I found the error as I described in the above message. Let me know if something was unclear. Please fix the mentioned  bug and then come with detailed steps to reproduce.

**Comment by danieldahan** [comment] 2020-11-22 19:04
Not sure what code you debugged of mine, I only put an insert statement for you to look at. If you would like to try and see if it breaks go ahead, if not, then I'll fix your library and send a PR.

**Comment by dmonad** [comment] 2020-11-22 21:33
I explained above that the issue was related to the JSON encoding that is used in the slate examples. Michaels code was very helpful in finding the underlying problem. I closed the ticket because it was not a problem in the Yjs library or any other packages that I maintain (I'm not the maintainer of slate-yjs). I also gave an in-depth explanation of why the error is produced.

I tried out your code just now and it does work as expected.

I'm very explicit in the issue template that I need to be able to reproduce the error. I hope that you understand my mild outburst since you ignored my issue template and provided no information to reproduce the error - for a second time. 

It's all fine. I'd be happy if you find the issue and provide a PR. You are also free to open another ticket (filling out the issue template).

**Comment by danieldahan** [comment] 2020-11-22 21:35
I am not using slate, you have never seen my code. Look at the account, I am not the slate guy.

**Comment by dmonad** [comment] 2020-11-22 21:37
Yeah.. that's my problem. I don't know what you are doing. You need to send me reproducible examples ;)

(and yes, sorry I mistook you for the person who posted the code)

**Comment by dmonad** [comment] 2020-11-22 21:42
Also as said.. I tried out your code and it does work in https://demos.yjs.dev/codemirror/codemirror.html (using the y-webrtc provider). I know my code well enough to understand that this code will work as expected. Feel free to open a PR if you find anything. Also feel free to open another ticket. There is no need to exchange arguments here. As said, it's all fine on my side & I'd be happy to collaborate with you in the future.

**Comment by danieldahan** [comment] 2020-11-22 21:47
@dmonad I am not arguing, I am trying to identify that I am not the person you thought. It took more messages to do that than to get a dialog about your product going. My goal is to help make your library amazing as I am using it. So there are no issues, and I am happy to collaborate as well. That said, I am happy the issue is not with your library, it will be easier to diagnose the issue. Also, I added to this issue because I started it and wrote that I would come back if I found anything further. Anyway.... all good, and thank you for the great library... I only want to see it do well.

**Comment by danieldahan** [comment] 2020-11-23 20:18
For anyone who is following the thread. The issue as to why the Yjs update was breaking, was not actually because of Yjs, it was because in the encode and decode process, I was passing a Map to the `applyUpdate` method, which had Uint8Array type key/value pairs, but was not actually an Uint8Array. I imagine that a `length` call for lengthly strings was somewhere called and returned `undefined`, causing the breakage. I will need to investigate the internals of the encoding process using `encodeStateAsUpdate` to see why this has happened.

**Comment by dmonad** [comment] 2020-11-23 20:59
Thanks for the update!

The `.subarray` method is used for string decoding (**) and for decoding of binary data. Anything array-like is probably fine until your document grows above a certain size. 

(**): There are essentially two string decoders. A fast one that decodes smaller potions of texts. Another one that decodes text as soon as the text-size exceeds a certain limit. The latter is based on TextDecoder which expects an Uint8Array as input. The Uint8Array is generated using the `.subarray` method.

I depend on other Uint8Array-methods. It's interesting that so far it only hit the `.subarray` method.

One approach to guard against this type of mistake would be to check the constructor before accepting the Uint8Array. I was hoping that the typescript type-checker would catch this type of error. I will think about this..

**Comment by danieldahan** [comment] 2020-11-23 21:15
It is exactly like that... an Array like Object literal where the keys are contiguous keys *0, 1, ..., n - 1,*. Once the length was around 900+, it hit the *subarray* method. I am going to write my own websocket layer... as I have some demands that the out of box one won't handle for me.... if I come across a neat idea for handling this, I will share further. Thanks for the confirmation of my findings :)
