### ISSUE TITLE
Undoing deletions sometimes not working

### ISSUE THREAD

**Issue by ISNIT0** [yjs/yjs#204] opened 2020-05-20 11:34 UTC
- Yjs@13.0.8

```javascript
(async function () {
    const doc = new Y.Doc();
    const text = doc.getText('quill');
    text.insert(0, 'Hello World');
    const um = new Y.UndoManager(text);
    text.delete(0, 5);

    const newDoc = new Y.Doc();
    Y.applyUpdate(newDoc, Y.encodeStateAsUpdate(doc));

    const newText = newDoc.getText('quill');

    newText.insert(0, '123');

    const newUm = new Y.UndoManager(newText);
    newUm.undoStack = um.undoStack;

    while (newUm.undoStack.length) {
        newUm.undo();
    }

    console.log(newText.toString()); // expect ~"Hello 123 World"
})();
```

The undos seem to work on document additions:
```javascript
(async function () {
    const doc = new Y.Doc();
    const text = doc.getText('quill');
    const um = new Y.UndoManager(text);
    text.insert(0, 'Hello World');

    const newDoc = new Y.Doc();
    Y.applyUpdate(newDoc, Y.encodeStateAsUpdate(doc));

    const newText = newDoc.getText('quill');

    newText.insert(0, '123');

    const newUm = new Y.UndoManager(newText);
    newUm.undoStack = um.undoStack;

    while (newUm.undoStack.length) {
        newUm.undo();
    }

    console.log(newText.toString()); // expect "123"
})();
```

**Comment by ISNIT0** [comment] 2020-05-21 13:36
For future reference:
@dmonad Explained that I had to disable GC for the docs (deleted content gets removed from doc structure when there is no UndoManager referring to them otherwise) - `new Y.Doc({ gc: false })`

This means mean docs could get very large over time.
What I'll do to prevent this is retain recent deletions, but let Yjs gc older deletions.
I think something like this will work (@dmonad would appreciate your guidance if I'm wrong):
```javascript
const doc = new Y.Doc({gc:false});

const undoStacks = getRecentUndoStacks();

for(const stack of undoStacks) {
  const um = new Y.UndoManager(doc);
  um.undoStack = stack;
}

Y.applyUpdate(doc, documentState);
const newDocumentState = Y.encodeStateAsUpdate(doc); // Should have GC'd any deletions not referenced in undoStacks
```

**Comment by dmonad** [comment] 2020-06-02 16:52
Here is a complete example on how you can keep the deleted structures and keep the rest. It is important to do this at the beginning right after the document is initialized.

```js
// do not garbage collect updates
// we enable it later after items referred by the stacks are marked as `keep` (preserving them so their content can be restored)
const ydoc = new Y.Doc({ gc: false })

// apply initial document content
Y.applyUpdate(ydoc, initialContent)

/**
 * This is a helper function that marks an item as `keep`.
 *
 * Make sure that neither item nor any of its parents is ever deleted.
 *
 * This property does not persist when storing it into a database or when
 * sending it to other peers
 *
 * @param {Item|null} item
 * @param {boolean} keep
 */
export const keepItem = (item, keep) => {
  while (item !== null && item.keep !== keep) {
    item.keep = keep
    item = item.parent._item
  }
}

// mark items as `keep`
ydoc.transact(t => {
  for (const stack of undoStacks) {
    // make sure that deleted structs are not gc'd
      Y.iterateDeletedStructs(transaction, stack.ds, item => {
        if (item instanceof Y.Item)) {
          keepItem(item, true)
        }
      })
  }
})

// Now that all referred items are marked as `keep`, we can enable gc again
ydoc.gc = true

```

**Comment by dmonad** [comment] 2020-06-02 16:53
The behavior you are describing is not a bug, so I'm going to close this issue.

**Closed by dmonad** 2020-06-02 16:53 UTC
Labels: bug
