### ISSUE TITLE
Typing of Y.Map only cover values

### ISSUE THREAD

**Issue by kirill-konshin** [yjs/yjs#362] opened 2021-12-14 22:07 UTC
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**

Current declaration only allows to set type of values, not keys:

```ts
export class YMap<MapType> extends AbstractType<YMapEvent<MapType>> implements Iterable<MapType> {
```

But what if I know for sure which keys and values `Map` can have?

**Describe the solution you'd like**

```ts
type MyType = {id: string; foo: string; bar: number};
const map = new Y.Map<MyType>(...);
const id = map.get('id') // return value should be known to be string
```

The code above will result in `id` variable to have type `MyType` which is confusing and not what expected.

**Comment by dmonad** [comment] 2021-12-14 22:31
Unfortunately, typescript doesn't support this kind of typing. If you can show me how to do the same with the native `Map`, we can continue talking.

This is a duplicate of #352 .

**Closed by dmonad** 2021-12-14 22:31 UTC
Labels: enhancement
