### ISSUE TITLE
 transaction.subdocsAdded not defined in certain transactions

### ISSUE THREAD

**Issue by disarticulate** [yjs/yjs#270] opened 2021-01-02 21:27 UTC
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
transaction.subdocs is undefined. Based on my full upgrade of the subcomponents y-webrtc and yjs, it's likely there were two version of yjs operating, although I'm using a custom compiled minified script here: https://github.com/disarticulate/yjs which would explain partially why there'd be two different ones loaded. the minified script is to use in webworker to improve cache usage. tbh, I'm not sure where the other version was coming from. I upgraded everything and it's gone.

```
      transaction.subdocsAdded.forEach(subdoc => doc.subdocs.add(subdoc));
      transaction.subdocsRemoved.forEach(subdoc => doc.subdocs.delete(subdoc));
```
stack trace
```
cleanupTransactions (yjs.mjs?7428:3043)
cleanupTransactions (yjs.mjs?7428:3053)
transact (yjs.mjs?7428:3092)
readUpdateV2 (yjs.mjs?7428:1555)
applyUpdateV2 (yjs.mjs?7428:1587)
applyUpdate (yjs.mjs?7428:1601)
readSyncStep2 (sync.js?a72f:82)
readSyncMessage (sync.js?a72f:116)
readMessage (y-webrtc.js?9b73:76)
(anonymous) (y-webrtc.js?9b73:333)
(anonymous) (mutex.js?c98a:35)
(anonymous) (y-webrtc.js?9b73:332)
Promise.then (async)
Room._bcSubscriber (y-webrtc.js?9b73:331)
eval (broadcastchannel.js?fadf:104)
publish (broadcastchannel.js?fadf:104)
eval (y-webrtc.js?9b73:249)
eval (mutex.js?c98a:35)
eval (y-webrtc.js?9b73:248)
Promise.then (async)
broadcastBcMessage (y-webrtc.js?9b73:247)
connect (y-webrtc.js?9b73:391)
eval (y-webrtc.js?9b73:579)
Promise.then (async)
WebrtcProvider (y-webrtc.js?9b73:576)
whenSynced (Manifest.js?bba8:46)
{...}
```

**To Reproduce**
No idea aside from using mismatched yjs prior to https://github.com/yjs/yjs/issues/234 upgrade.

**Environment Information**
- minified version shown here: https://github.com/disarticulate/yjs [it was upgraded, the prior version script was local]

**Additional context**
full upgrade solved the issue. usually yjs detects incompatible versions, so it may be useful to extend that to this change.

**Comment by dmonad** [comment] 2021-01-03 15:31
Hi @disarticulate ,

> usually yjs detects incompatible versions, so it may be useful to extend that to this change.

It does not. But it is critical that you only use one Yjs version in your project. All dependencies (e.g. y-webrtc) specify Yjs as a peerDependency to avoid this problem.

Since there is no way for me to reproduce this issue, I'm going to close this ticket. If you can reproduce this issue in a different environment, then please open another ticket, or reopen this one.

**Closed by dmonad** 2021-01-03 15:31 UTC
Labels: bug
