### ISSUE TITLE
Y.Text arrives in a "broken" state after update if "\r" carriage return exists inside the content

### ISSUE THREAD

**Issue by ionutpasca** [yjs/yjs#436] opened 2022-06-15 16:32 UTC
**Checklist**

* [x ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**

**Info**: We have a monaco editor instance inside our product and we are using the Y.Text shared type in order to store the file content and provide real time collaboration between the users. 

**Problem**: The Y.Text content is different after a refresh is made (the bind between the editor and the Y.Text is no longer up to date).
We could actually reproduce this problem after a paste of some content was done inside the editor. We noticed that the content that was pasted contained "\r\n" and "\r" carriage return, instead of only "\n".  After paste, the editor worked fine, but after we reloaded the content from the Y.Text, it was noticed that the content was not what we expected it to be.

**Used Content:**
_import React from "react"; \r\nconst Test = () => {    \r\n return null\n}\n\nexport default Test\n_

I was able to reproduce this on the collaborative editor provided in your platform.

https://user-images.githubusercontent.com/11486739/173878439-cbf4c659-46e8-451f-8e37-5a94190c6347.mov

**To Reproduce**
1. Go to https://docs.yjs.dev/getting-started/a-collaborative-editor and scroll to the collaborative editors
2. In the first editor (the one on top), on line 35 (after getting the text from the ydoc), add this line: `ytext.insert(0, `import React from "react"; \r\nconst Test = () => {    \r\n return null\n}\n\nexport default Test\n`)`. This is a dummy react component.
4. Make some changes inside the component (in the right editor)
5. Refresh the editor

**Expected behavior**
The content from the editor should be the same after refresh

**Environment Information**
 - Chrome

**Comment by dmonad** [comment] 2022-06-16 07:35
This seems to be a duplicate of https://github.com/yjs/y-monaco/issues/6

**Closed by dmonad** 2022-06-16 07:35 UTC
Labels: bug
