### ISSUE TITLE
Support for TypeScript NodeNext

### ISSUE THREAD

**Issue by oriSomething** [yjs/yjs#602] opened 2023-11-26 20:04 UTC
Yjs has problematic definition to support TypeScript module resolution of `NodeNext`. There should be separate definitions for commonjs export and module export (something as the example):

```
"exports": {
    ".": {
      "import": {
        "types": "./dist/index.d.ts",
        "default": "./dist/index.js"
      },
      "require": {
        "types": "./dist/index.d.cts",
        "default": "./dist/index.cjs"
      }
    },
```

I've notice it while trying to fix similar issues with Lexical library, where I get this error when trying to use `NodeNext`:

__packages/lexical-yjs/src/SyncEditorStates.ts(22,71): error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("yjs")' call instead.__

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Comment by dmonad** [comment] 2023-11-27 13:09
Please fill out the issue template. Otherwise I won't bother trying to reproduce this. Which TS version? Which Yjs version? How to reproduce (ideally you describe a minimal reproducible example)? ..

Gesendet von ProtonMail mobile

-------- Original Message --------

**Comment by dmonad** [comment] 2023-11-27 15:48
Closing since this probably already fixed

**Closed** 2023-11-27 15:48 UTC
Labels: bug
