### ISSUE TITLE
TypeError: Y.Doc is not a constructor

### ISSUE THREAD

**Issue by david-istvan** [yjs/yjs#245] opened 2020-09-28 21:46 UTC
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
"TypeError: Y.Doc is not a constructor" when trying to execute the example in the README.

**Environment Information**
 - Node.js
 - Yjs version: yjs@13.3.2

**Comment by dmonad** [comment] 2020-09-28 21:50
Hey @david-istvan you need to bundle your project using some module bundler. I think it is unfortunate that modern libraries don't mention this fact anymore. 

We have several demo projects that already setup a working build system (really, any would work! - Yjs is not special in that regard). 

Simply clone/download https://github.com/yjs/yjs-demos and open any of the folders. Each folder includes a working demo application that uses webpack to build your application.

**Comment by dmonad** [comment] 2020-09-28 21:51
I'm going to close this ticket because I'm pretty sure that everything works as expected in that release - many people are using it. But let me know if you have any more questions.

**Closed by dmonad** 2020-09-28 21:51 UTC
Labels: bug

**Comment by david-istvan** [comment] 2020-10-12 20:27
I mean, why do you list code snippets [here](https://github.com/yjs/yjs) which won't work?

**Comment by dmonad** [comment] 2020-10-12 21:01
They do work.

I specifically ask in the ticket template that you give me clear steps on how to reproduce the issue. "X throws an error" is not enough because it is clearly working for other people. So you seem to do something differently..

I gave you a friendly reply and I offered a solution. You can reopen another ticket with clear steps to reproduce if you still want help.
