### ISSUE TITLE
When arrays are merged, the results are random?

### ISSUE THREAD

**Issue by a573367014** [yjs/yjs#306] opened 2021-05-29 13:52 UTC
**Describe the bug**
When arrays are merged, the results are random?
Because I found that the following code ends up with a length of 2 or 3

**To Reproduce**
```
import * as Y from 'yjs'

// user1
const ydoc1 = new Y.Doc();
const ymap1 = ydoc1.getMap();
let arr = new Y.Array();
arr.insert(0, [{type: 'text'}, {type: 'image'}]);
ymap1.set('elements', arr);

// user2
const ydoc2 = new Y.Doc();
const ymap2 = ydoc2.getMap();
arr = new Y.Array();
arr.insert(0, [{type: 'text'}, {type: 'image'}]);

ymap2.set('elements', arr);

ymap2.get('elements').push([{type: 'mask'}]);

const state1 = Y.encodeStateAsUpdate(ydoc1)
const state2 = Y.encodeStateAsUpdate(ydoc2)

Y.applyUpdate(ydoc1, state2)
Y.applyUpdate(ydoc2, state1)

console.log(ymap1.toJSON(), ymap2.toJSON())
```

**Expected behavior**
It seems that the more reasonable result length should be 3.

**Screenshots**

**Environment Information**
 - Chrome
 - yjs@13.5.8

**Additional context**

**Comment by dmonad** [comment] 2021-05-30 11:08
Hi @a573367014,

Y.Map implements a last-writer-wins key-value store. You have two distinct clients setting the `element` property at the same time. Either the insertion from user1 is used or the insertion from user 2. So you either end up with two or three elements

If you want that the concurrent insertions are merged, then you should make sure that both clients use the same Y.Array. E.g. by doing `ydoc.getArray('elements').insert(0, ..)`. This will avoid that another user overwrites your changes by setting a new Y.Array.

Closing because this is the expected behavior.

**Closed by dmonad** 2021-05-30 11:08 UTC
Labels: bug
